### PR TITLE
everything compressed and decoded aysnc

### PR DESCRIPTION
**Pull request by dmfenton**
@ngoldman I'm kinda torn here about whether I should use a [backport](https://www.npmjs.com/package/node-zlib-backport) or go async what do you think?

### CODE REVIEW

**Comment by ungoldman** [comment]
What's the advantage of the synchronous method? Isn't it potentially blocking the process on an expensive job?

**Comment by dmfenton** [comment]
Cleaner syntax.

And no it shouldn't block anything in practice. _decode is a private method called by a different async function.

**Comment by ungoldman** [comment]
I'd say we can refactor to use sync when we move to 0.12 rather than adding another dependency now just for the sake of syntax.

**Comment by dmfenton** [comment]
Cool with me

**Pull request merged**
